export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILED = 'FETCH_CONTACTS_FAILED';

export const CHANGE_CONTACTS_PROPS = 'CHANGE_CONTACTS_PROPS';
export const CHANGE_FAV_CONTACTS_PROPS = 'CHANGE_FAV_CONTACTS_PROPS';

export const ADD_AS_SELECTED_CONTACT = 'ADD_AS_SELECTED_CONTACT';
export const REMOVE_SELECTED_CONTACT = 'REMOVE_SELECTED_CONTACT';

export const SAVE_USER_INFORMATION = 'SAVE_USER_INFORMATION';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_AUTH_PROPS = 'CHANGE_AUTH_PROPS';
export const IS_RESEND_BUTTON_EXIST = 'IS_RESEND_BUTTON_EXIST';
export const RESET_TIMER = 'RESET_TIMER';
